CREATE DATABASE IF NOT EXISTS phonevault;

USE phonevault;


CREATE TABEL IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL
);
